# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SearchForPlayer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.8.1'
  pod 'AlamofireImage', '~> 3.5.0'
  pod 'Bolts'

  pod 'Firebase/Core'#, '~> 5.16.0'
  pod 'Firebase/Messaging'#, '~> 3.2.1'
  pod 'Firebase/RemoteConfig'#, '~> 3.1.0'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'FirebaseUI'
  

  # Pods for SearchForPlayer

end
