# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '11.0'

target 'SearchForPlayer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Alamofire', '~> 4.8.0'
  pod 'Bolts'
  pod 'Cosmos'#, '~> 17.0.0'
  pod 'ESPullToRefresh'#, '2.7'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Firestore'
  #pod 'Firebase/Messaging'
  pod 'Firebase/RemoteConfig'
  
  
  #pod 'Geofirestore'

  pod 'GoogleMaps'#, '~> 3.1.0'
  pod 'GooglePlaces'#, '~> 3.1.0'
  pod 'GooglePlacePicker'#, '~> 3.1.0'
  
  pod 'GestureRecognizerClosures'#, '~> 4.1.0'
  
  pod 'IBAnimatable'#, '~> 5.2.1'
  pod 'IQKeyboardManager'#, '~> 6.2.0'
  #pod 'IGListKit', '~> 3.4.0'
  
  pod 'ImageSlideshow', '~> 1.7.0'
  #pod 'ImageSlideshow/AFURL'
  #pod 'ImageSlideshow/Alamofire'
  #pod 'ImageSlideshow/SDWebImage'
  #pod 'ImageSlideshow/Kingfisher'
  #pod 'JTAppleCalendar'
  pod 'JTCalendar'
  
  pod 'Kingfisher', '~> 4.10.1'
  pod 'Moya'#, '~> 12.0.1'
  
  pod 'ObjectMapper'#, '~> 3.3.0'
  
  #pod 'RAMAnimatedTabBarController'
  pod 'ReachabilitySwift'#, '~> 4.3.0'
  pod 'RealmSwift', '~> 3.11.2'
  pod 'RealmModels', '0.1.0'
  pod 'RxSwift'#,    '~> 4.4.1'
  pod 'RxCocoa'#,    '~> 4.4.1'

  pod 'Popover'#, '~> 1.2.2'
  
  pod 'SDWebImage'#, '~> 4.4.2'
  pod 'SearchTextField'#, '~> 1.2.2'
  pod 'SloppySwiper'#, '~> 0.6'
  pod 'SVProgressHUD'#, '~> 2.2.5'
  
  pod 'SnapKit'#, '~> 4.0.1'
  
  pod 'StarRatingView'#, '~> 1.3.0'
  
  pod 'SwiftDate'#, '~> 5.1.0'
  
  pod 'XLPagerTabStrip'
  pod 'YoutubeDirectLinkExtractor'

  # Pods for SearchForPlayer

end
